# Generated by Django 3.2.9 on 2021-11-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('potencia', models.IntegerField()),
                ('cilindrada', models.CharField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('passageiros', models.IntegerField()),
                ('publicacao', models.DateTimeField(auto_now_add=True)),
                ('fabricacao', models.IntegerField()),
            ],
        ),
    ]
