# Generated by Django 3.2.9 on 2021-12-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('rg', models.CharField(max_length=16, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
    ]
